home:
    pattern: /
    controller: Sakura

sakura:
    pattern: /sakura(/id)
    controller: Sakura

sakuras:
    pattern: /sakuras
    controller: Sakuras

locations:
    pattern: /locations
    controller: Locations
